{% set name = "m2r2" %}
{% set version = "0.3.3.post2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/m2r2-{{ version }}.tar.gz
  sha256: e62bcb0e74b3ce19cda0737a0556b04cf4a43b785072fcef474558f2c1482ca8

build:
  number: 1
  noarch: python
  entry_points:
    - m2r2 = m2r2:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mistune ==0.8.4
    - docutils >=0.19

test:
  imports:
    - m2r2
  commands:
    - pip check
    - m2r2 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/crossnox/m2r2
  summary: Markdown and reStructuredText in a single file.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
    - xylar
