schema_version: 1

context:
  name: m2r2
  version: "1.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/m2r2-${{ version }}.tar.gz
  sha256: 998534cc1b6d0542483c976a5387f2d7d2223361fb637ca1d1d733571d5e6db0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - m2r2 = m2r2:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - mistune >=3.0,<3.3
    - docutils >=0.19

tests:
  - python:
      imports:
        - m2r2
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - m2r2 --help

about:
  summary: Markdown and reStructuredText in a single file.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/crossnox/m2r2

extra:
  recipe-maintainers:
    - basnijholt
    - xylar
